### ISSUE TITLE
PART1 / 1장 어떤 개발자가 될 것인가?

### ISSUE THREAD

**Issue by ChanKyeol** [ChanKyeol/silhakdan#3]
PART1 개발자가 되려는 이유를 확실히 정하자

**Comment by coldMater** [comment]
좋아 잘했어.

**Comment by coldMater** [comment]
자 이렇게 계속 하고, 혹시 이걸 본다면 오른쪽에 Assignees 에 너 자신을 할당해봐. Assign 은 할당하다 라는 뜻이고 Assignee 는 ee 붙었으니까 할당'된 사람' 을 의미하겠지?
